spring:
#  boot:
#    admin:
#      client:
#        url: "http://localhost:8788"
  application:
    name: admin-client
  security:
    user:
      name: admin
      password: admin
eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: "http://${spring.security.user.name}:${spring.security.user.password}@localhost:8660/eureka"
  instance:
    lease-renewal-interval-in-seconds: 10
    health-check-url-path: /actuator/health
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
server:
  port: 8880
